// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ResearchWeb.Data;

#nullable disable

namespace ResearchWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260825141021_PostgreSQLInitialCreate")]
    partial class PostgreSQLInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ResearchWeb.Models.Research2026", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("اسم_الباحث")
                        .HasColumnType("text");

                    b.Property<DateTime?>("تاريخ_الاجتماع")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("توصيات_اللجنة")
                        .HasColumnType("text");

                    b.Property<string>("رقم_الاجتماع")
                        .HasColumnType("text");

                    b.Property<string>("رقم_البحث")
                        .HasColumnType("text");

                    b.Property<string>("رقم_الهاتف")
                        .HasColumnType("text");

                    b.Property<string>("عنوان_البحث")
                        .HasColumnType("text");

                    b.Property<string>("نتيجة_البحث")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("الابحاث العلمية 2026", (string)null);
                });

            modelBuilder.Entity("ResearchWeb.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ResearchWeb.Models.Visitor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.ToTable("Visitors", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
