// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResearchWeb.Data;

#nullable disable

namespace ResearchWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ResearchWeb.Models.Research", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("اسم_الباحث")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("تاريخ_الاجتماع")
                        .HasColumnType("TEXT");

                    b.Property<string>("توصيات_اللجنة")
                        .HasColumnType("TEXT");

                    b.Property<string>("رقم_الاجتماع")
                        .HasColumnType("TEXT");

                    b.Property<string>("رقم_البحث")
                        .HasColumnType("TEXT");

                    b.Property<string>("رقم_الهاتف")
                        .HasColumnType("TEXT");

                    b.Property<string>("عنوان_البحث")
                        .HasColumnType("TEXT");

                    b.Property<string>("نتيجة_البحث")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("الابحاث العلمية 2026", (string)null);
                });

            modelBuilder.Entity("ResearchWeb.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
